name: HAProxy
version: 1.0.0
slug: haproxy
description: HAProxy reverse proxy
arch:
  - aarch64
  - amd64
  - armv7
init: false
map:
  - addon_config:ro
  - ssl
ports:
  443/tcp: 443
  80/tcp: 80
ports_description:
  443/tcp: HTTPS
  80/tcp: HTTP
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  certfile: str
  keyfile: str
